# Generated by Django 5.2.1 on 2025-05-22 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('kilometrage', models.CharField(max_length=100)),
                ('type_carburant', models.CharField(max_length=100)),
                ('boite_a_vitesse', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('a_vendre', models.BooleanField(default=False)),
                ('a_louer', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rôle', models.CharField(default='client', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ImageField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ImageField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vente')),
            ],
        ),
    ]
