# Generated by Django 5.2.1 on 2025-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='contract',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
