# Generated by Django 5.2.1 on 2025-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vente_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contract',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
