# Generated by Django 5.2.1 on 2025-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_location_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='cout_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
