# Generated by Django 5.2.1 on 2025-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_location_statut_vente_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
