# Generated by Django 5.2.1 on 2025-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_location_contract_alter_vente_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
